# Generated by Django 6.0.1 on 2026-02-04 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='purchase_cost',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='condition_on_return',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='due_back',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='details',
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.assetcategory'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.department'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
