# Generated by Django 6.0.1 on 2026-02-04 13:43

import django.db.models.deletion
from django.db import migrations, models


def populate_assetcategory_codes(apps, schema_editor):
    AssetCategory = apps.get_model('assets', 'AssetCategory')
    for category in AssetCategory.objects.all().order_by('id'):
        if not category.code:
            category.code = f"C{category.pk:04d}"
            category.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_asset_notes_remove_asset_purchase_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RunPython(
            code=populate_assetcategory_codes,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.department'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='assets.asset'),
        ),
    ]
