# Generated by Django 6.0.1 on 2026-02-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assetcategory_code_alter_asset_asset_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
