# Generated by Django 6.0.1 on 2026-02-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_assetcategory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(help_text='Unique asset identification code', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='code',
            field=models.CharField(default='TEMP', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
