# Generated by Django 6.0.1 on 2026-02-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_asset_asset_tag_alter_assetcategory_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(auto_created=True, max_length=50, unique=True)),
            ],
        ),
    ]
