# Generated by Django 6.0.1 on 2026-02-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_assettag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetTag',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(auto_created=True, help_text='Unique asset identification code', max_length=50, unique=True),
        ),
    ]
