# Generated by Django 6.0.1 on 2026-02-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_delete_assettag_alter_asset_asset_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
        migrations.AddField(
            model_name='asset',
            name='assignment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='AssetAssignment',
        ),
        migrations.DeleteModel(
            name='AssetCategory',
        ),
    ]
