# Generated by Django 6.0.1 on 2026-02-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_remove_asset_category_asset_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='assignment',
        ),
    ]
