# Generated by Django 6.0.3 on 2026-03-19 19:11

from django.db import migrations, models


def normalize_blank_barcodes(apps, schema_editor):
    Asset = apps.get_model('assets', 'Asset')
    Asset.objects.filter(barcode='').update(barcode=None)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_alter_asset_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.RunPython(normalize_blank_barcodes, migrations.RunPython.noop),
    ]
