# Generated by Django 6.0.3 on 2026-04-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_generate_missing_asset_barcodes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='category',
            name='code',
        ),
    ]
