# Generated by Django 6.0.3 on 2026-03-19 19:08

from django.db import migrations, models


ROLE_GROUP_MAP = {
    'admin': 'Admin',
    'dean': 'Dean',
    'cod': 'COD',
    'lecturer': 'Lecturer',
    'lab_technician': 'Lab Technician',
}

LEGACY_GROUP_ROLE_MAP = {
    'system_admin': 'admin',
    'Faculty Administrator': 'admin',
    'administrator': 'admin',
    'Dean of Faculty': 'dean',
    'dean': 'dean',
    'chair_department': 'cod',
    'Chair of Department': 'cod',
    'cod': 'cod',
    'lecturer_staff': 'lecturer',
    'lecturer': 'lecturer',
    'technician': 'lab_technician',
    'Lab Technician': 'lab_technician',
}


def bootstrap_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('accounts', 'Profile')

    for group_name in ROLE_GROUP_MAP.values():
        Group.objects.get_or_create(name=group_name)

    for user in User.objects.all():
        role = ''
        if user.is_superuser:
            role = 'admin'
        else:
            names = set(user.groups.values_list('name', flat=True))
            for name in names:
                role = LEGACY_GROUP_ROLE_MAP.get(name, '')
                if role:
                    break

        profile, _ = Profile.objects.get_or_create(user=user)
        if role and not profile.role:
            profile.role = role
            profile.save(update_fields=['role'])

        if profile.role:
            group_name = ROLE_GROUP_MAP.get(profile.role)
            if group_name:
                group = Group.objects.get(name=group_name)
                user.groups.add(group)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('dean', 'Dean'), ('cod', 'COD'), ('lecturer', 'Lecturer'), ('lab_technician', 'Lab Technician')], max_length=30),
        ),
        migrations.RunPython(bootstrap_roles, migrations.RunPython.noop),
    ]
