# Generated by Django 6.0.3 on 2026-03-11 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0011_supplier_remove_asset_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_return_date', models.DateField()),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField()),
                ('condition_out', models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('unserviceable', 'Unserviceable')], max_length=20)),
                ('condition_in', models.CharField(blank=True, choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('unserviceable', 'Unserviceable')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='active', max_length=20)),
                ('allocated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations_made', to=settings.AUTH_USER_MODEL)),
                ('allocated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations_received', to=settings.AUTH_USER_MODEL)),
                ('allocated_to_lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_allocations', to='assets.location')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='assets.asset')),
            ],
            options={
                'ordering': ['-allocation_date'],
            },
        ),
    ]
